server:
  port: 10500

spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  cloud:
    bus:
      refresh:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: info
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    bus-refresh:
      enabled: true


