spring:
  application:
    name: oauth-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
      label: master
      name: oauth-server
    bus:
      enabled: true


eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    health-check-url-path: /actuator/health
    ip-address: 139.9.206.164
  client:
    serviceUrl:
      defaultZone: http://139.9.206.164:8761/eureka/
